version: '3.8'

services:
  app:
    # Using image from GitLab container registry - the latest master build
    image: gitlab.fit.cvut.cz:5050/etcs/simemulator:master
    ports:
      - "5900:5900"
    working_dir: /app
    restart: on-failure
    volumes:
      - ./secrets/database:/app/secrets/database
      - ./secrets/mqtt:/app/secrets/mqtt
      - ./configuration.py:/app/configuration.py
    environment:
      DATABASE_CREDENTIALS_FILE: ./secrets/database/config.json
      MQTT_CREDENTIALS_FILE: ./secrets/mqtt/config.json
    depends_on:
      mqtt:
          condition: service_started
      database:
          condition: service_healthy

  mqtt:
    image: eclipse-mosquitto
    volumes:
      # use config file that sets broker to accept anonymous clients
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # mosquitto.conf file should contain following lines to enable connection from other containers
      #     listener 1883
      #     allow_anonymous true
    ports:
      - "1883:1883"

  database:
    image: mysql:8.1
    volumes:
      - ./db/2023-03-11/2023-03-11.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'infradb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # Show errors only
    command: --log-error-verbosity=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot", "-h", "database"]
      interval: 4s
      timeout: 4s
      retries: 80
      start_period: 8s
