version: '3.8'

services:
  app:
    image: sim-emulator
    ports:
      - "5900:5900"
    working_dir: /app
    volumes:
      - ./secrets/database:/app/secrets/database
      - ./secrets/mqtt:/app/secrets/mqtt
      - ./configuration.py:/app/configuration.py
    environment:
      DATABASE_CREDENTIALS_FILE: ./secrets/database/docker_compose.json
      MQTT_CREDENTIALS_FILE: ./secrets/mqtt/docker_compose.json
    depends_on:
      mqtt:
          condition: service_started
      database:
          condition: service_healthy

  mqtt:
    image: eclipse-mosquitto
    volumes:
      # use config file that sets broker to accept anonymous clients
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      # mosquitto.conf file should contain following lines to enable connection from other containers
      #     listener 1883
      #     allow_anonymous true
    ports:
      - "1883:1883"

  database:
    image: mysql
    volumes:
      - ./db/2023-03-11/2023-03-11.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # noinspection SpellCheckingInspection
      MYSQL_DATABASE: 'infradb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    healthcheck:
      # noinspection SpellCheckingInspection
      test: ["CMD", "mysqladmin", "ping", "-proot", "-h", "database"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 30s